name: Build and Deploy

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - name: Install JS dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: |
          yarn next build
          yarn next export
        env:
          NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID}}
          NEXT_PUBLIC_CRISP_WEBSITE_ID: ${{ secrets.CRISP_WEBSITE_ID}}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: out
